export enum Status {
  RECEBIDO = 'RECEBIDO',
  AGUARDANDO_PAGAMENTO = 'AGUARDANDO_PAGAMENTO',
  NOTA_FISCAL_EMITIDA = 'NOTA_FISCAL_EMITIDA',
  PRODUTO_EM_SEPARACAO = 'PRODUTO_EM_SEPARACAO',
  PRODUTO_ENVIADO = 'PRODUTO_ENVIADO',
  CONCLUIDO = 'CONCLUIDO',
  CANCELADO = 'CANCELADO'
}